"""empty message

Revision ID: 55db12235590
Revises: e4f354eb09ff
Create Date: 2023-03-20 22:59:32.319219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55db12235590'
down_revision = 'e4f354eb09ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('enviado_por_cliente', sa.Boolean(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensaje')
    # ### end Alembic commands ###
