"""empty message

Revision ID: 5ab4210a9795
Revises: eda7e3bc365b
Create Date: 2023-03-18 00:21:24.763810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab4210a9795'
down_revision = 'eda7e3bc365b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repartidor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=100), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('direccion_entrega', sa.String(length=200), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('repartidor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['repartidor_id'], ['repartidor.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), server_default=sa.text("('')"), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    op.drop_table('pedido')
    op.drop_table('repartidor')
    # ### end Alembic commands ###
