"""crea la tabla usuario

Revision ID: 7dc59205402d
Revises: 098992df8c62
Create Date: 2023-03-19 02:21:54.994912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc59205402d'
down_revision = '098992df8c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitud', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.Float(), nullable=True))
        batch_op.alter_column('producto',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('direccion_entrega',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('direccion_entrega',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('producto',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')

    # ### end Alembic commands ###
