"""empty message

Revision ID: a1e90f2fe69e
Revises: 7dc59205402d
Create Date: 2023-03-20 00:58:41.858582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e90f2fe69e'
down_revision = '7dc59205402d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repartidor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=32), nullable=False, server_default='repartidor'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repartidor', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
