"""empty message

Revision ID: e4f354eb09ff
Revises: c234b27abc6c
Create Date: 2023-03-20 22:28:46.623414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f354eb09ff'
down_revision = 'c234b27abc6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repartidor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubi_lat_repartidor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ubi_long_repartidor', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repartidor', schema=None) as batch_op:
        batch_op.drop_column('ubi_long_repartidor')
        batch_op.drop_column('ubi_lat_repartidor')

    # ### end Alembic commands ###
